from aoc08 import q1, q2, parse_input_08


def test_q1():
    raw_input = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""
    input = parse_input_08(raw_input)
    assert q1(input) == 14

    assert q2(input) == 34
